#FILL IN OWN CREDENTIALS

spring.mail.host : smtp.gmail.com
spring.mail.port : 587
spring.mail.username: nessaek@gmail.com
spring.mail.password: 1Loaded!ggg


dialogflow:
  project-id: quick-filament-272623
  session-id: 6544039d-c080-428e-b9e6-524f065a7bbe
  language-code: en-GB

#NOT FINISHED

spring.mail.properties.smtp:
  auth: true
  starttls.enable: true
  starttls.required: true
  socketFactory.port: 465
  socketFactory.class: javax.net.ssl.SSLSocketFactory
  socketFactory.fallback: false
