#FILL IN OWN CREDENTIALS

spring.mail.host : [YOUR_MAIL_HOST]
spring.mail.port : [YOUR_MAIL_PORT]
spring.mail.username: [YOUR_EMAIL_ADDRESS]
spring.mail.password: [YOU_PASSWORD]


spring.mail.properties.smtp:
  auth: true
  starttls.enable: true
  starttls.required: true
  socketFactory.port: 465
  socketFactory.class: javax.net.ssl.SSLSocketFactory
  socketFactory.fallback: false
